services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: omarya
      POSTGRES_PASSWORD: changeinprod
      POSTGRES_DB: postgres

# Connect to DB w/ "docker exec -it finsightapi-db-1 psql -U omarya postgres"