version: '3.8'

services:
  backend:
    build: ./finsightapi
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=omarya
      - POSTGRES_PASSWORD=changeinprod
      - POSTGRES_DB=postgres
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: omarya
      POSTGRES_PASSWORD: changeinprod
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"