spring:
    application:
        name: finsightapi
    datasource:
        url: jdbc:postgresql://finsightapi-db.internal:5432/postgres
        username: postgres
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    address: 0.0.0.0
    port: 8080