name: Update Asset Prices

on:
  schedule:
    # Run at 06:00 UTC (2:00 AM EST) daily
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-prices:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install dependencies
      run: cd finsightapi && mvn clean install

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: cd frontend && npm install
    
    - name: Launch Spring Boot / React apps
      run: ./start.sh
    
    - name: Wait for apps (fixed duration)
      uses: actions/checkout@v3
      with:
        args: --single-branch --no-fetch -f sleep 20

    - name: Run update script
      run: cd frontend/src/api && node --loader ts-node/esm TwelveDataAPI.ts
      env:
        TD_PROD_KEY: ${{ secrets.TD_PROD_KEY }}