name: Update Asset Prices

on:
  schedule:
    # Run at 3:00 UTC (10:00 PM EST) daily
    - cron: '0 3 * * 1-5'
  workflow_dispatch:

jobs:
  update-prices:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
            - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt-hotspot'
        java-version: '17'

    - name: Install back end dependencies
      run: cd finsightapi && ./mvnw clean install -DskipTests

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'

    - name: Install front end dependencies
      run: cd frontend && npm install

    - name: Run update script
      run: cd frontend/src/api && node --loader ts-node/esm TwelveDataAPI.ts
      env:
        TD_PROD_KEY: ${{ secrets.TD_PROD_KEY }}